apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-prediction-api
  labels:
    app: traffic-prediction-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traffic-prediction-api
  template:
    metadata:
      labels:
        app: traffic-prediction-api
    spec:
      containers:
        - name: traffic-prediction-api-container
          image: sharjeelahmed017/traffic-prediction-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                secretKeyRef:
                  name: mlflow-secrets
                  key: tracking_uri
            - name: MLFLOW_TRACKING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mlflow-secrets
                  key: username
            - name: MLFLOW_TRACKING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-secrets
                  key: password
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: mlflow-secrets
                  key: sentry_dsn
