apiVersion: v1
kind: Service
metadata:
  name: traffic-prediction-api
spec:
  selector:
    app: traffic-prediction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30800
  type: NodePort
