# Global Configuration
project:
  name: "traffic-mlops"
  experiment_name: "Traffic_Vehicles_Regression_Experiment"

# Data Paths
data:
  raw_dir: "data/raw"
  raw_file: "data/raw/traffic.csv"
  processed_dir: "data/processed/clean_traffic_data"
  transformed_dir: "data/transformed"
  train_data: "data/transformed/train"
  test_data: "data/transformed/test"

# Artifact Paths
artifacts:
  models_dir: "models"
  pipeline_model: "models/pipeline"
  scores_file: "scores.json"
