---
# ConfigMap: shared environment variables for all services
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-traffic-config
  namespace: default
data:
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  API_URL: "http://fastapi-service:8000"
  PYSPARK_PYTHON: "python3"
  PYSPARK_DRIVER_PYTHON: "python3"